name: Code Formatter
on :
  push:
    branches:
      - readme
      - main
jobs:
  PEP8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.10
      - name: Install Python lint libraries
        run: |
          pip install autopep8 autoflake isort black
      - name: Check for showstoppers
        run: >
          autopep8 --verbose --in-place --recursive --aggressive --aggressive
          --ignore=W605 agrothon
      - name: Remove unused imports and variables
        run: >
          autoflake --in-place --recursive --remove-all-unused-imports
          --remove-unused-variables --ignore-init-module-imports .
      - name: lint with isort and black
        run: |
          isort agrothon
          black agrothon
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Code Auto Format"
          commit_options: "--no-verify"
          repository: .
          commit_user_name: Chandra Kiran Viswanath Balusu
          commit_user_email: 67821176+viswanathbalusu@users.noreply.github.com
          commit_author: Chandra Kiran Viswanath Balusu <67821176+viswanathbalusu@users.noreply.github.com>